### ISSUE TITLE
WEB EXAMPLE - Cleanup webstack repo

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_examplesite#41]
We need to clean up our webstack repo.

We now have 2 repos: webstack and examplesite that serves the same purpose

So let's:
- [x] move webstack content to examplesite
- [x] delete webstack repo when all it's content is moved 

Update examplesite with latest features/components/updates from farming:
- [x] components (simple header, navbar, headers etc) with all their latest updates from farming
- [x] blog/news/people/projects latest updates from farming (description pages, filtering, pagination etc)
- [x] add updated product component from threefold tech - mobile version

**Comment by ehab-hassan** [comment]
I think all components update according to farming website if there something missed please create issue individually we can fixed later
for webstack repo it's archived
