### ISSUE TITLE
WEB EXAMPLE - site update

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_examplesite#42]
Things missing:
- [x] product component is not showing on page2 - option to have image needs to be added to this component
- [x] need to add LinkedIn icon on navbar next to telegram icon
- [x] partner logos on home page needs to be clickable
- [x] large image component needs to be centred (its placed on left side for some reason)
- [x] for plans component (last one on page3) we have 'include' that gives green tick mark, can you plase check and insert in template what gives the opposite (exclude) mark? (i think it was gray ' - ' sign)
- [x] add filter on top for partners page
- [x] add pagination for team page
- [x] add pagination for partners page

**Comment by ehab-hassan** [comment]
@samaradel 
please check this
add filter on top for partners page
add pagination for team page
add pagination for partners page
