### ISSUE TITLE
ALL - update footer

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_examplesite#44]
![IMAGE 2021-03-18 15:55:11](https://user-images.githubusercontent.com/54844940/111629426-9022cd00-87f1-11eb-967d-011ee3a228c2.jpg)

Add all legal links to bottom like on polkadot 

![IMAGE 2021-03-18 15:55:20](https://user-images.githubusercontent.com/54844940/111629445-95801780-87f1-11eb-95f8-42df2ded1738.jpg)

that will include:
- impressum
- privacy policy
- terms & conditions 

- [x] see comment bellow and update example site and all websites with horizontal legal links on the bottom

- [x] Update links in vertical columns to remain in one line:

<img width="1440" alt="Screenshot 2021-03-19 at 17 48 03" src="https://user-images.githubusercontent.com/20182572/111807438-9beabe00-88db-11eb-9c11-9e7c42dc1710.png">

- [ ] Apply this update to example site and all websites

**Comment by Vilnite** [comment]
I updated ACI this way:

<img width="1237" alt="Screenshot 2021-03-19 at 17 21 45" src="https://user-images.githubusercontent.com/20182572/111803492-c2a6f580-88d7-11eb-9faf-de9c59f65263.png">

and works very nicely:

<img width="1440" alt="Screenshot 2021-03-19 at 17 24 15" src="https://user-images.githubusercontent.com/20182572/111803691-f4b85780-88d7-11eb-9f71-0678e3fdc761.png">

I couldn't get it to work for other websites though. 
Added all info in footer's markdown for all websites. 

Please make it work:
- [x] twin
- [x] cloud
- [x] marketplace
- [x] farming
- [x] threefold_io
- [x] threefold.tech
